[versions]
agp = "8.9.0"
kotlin = "1.9.24"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.0"
constraintlayout = "2.2.0"
ksp = "1.9.0-1.0.13"

# Lifecycle (ViewModel, LiveData)
lifecycle-runtime-ktx = "2.6.2"
lifecycle-viewmodel-ktx = "2.6.2"
lifecycle-livedata-ktx = "2.6.2"

# Navigation Component
navigation-fragment-ktx = "2.7.4"
navigation-ui-ktx = "2.7.4"

# Room Database
room-runtime = "2.5.2"
room-ktx = "2.5.2"
room-compiler = "2.5.2"

# Coroutines
coroutines-core = "1.7.3"
coroutines-android = "1.7.3"

# Retrofit (API Calling)
retrofit = "2.9.0"
retrofit-gson = "2.9.0"
okhttp-logging = "4.10.0"

# Hilt (Dependency Injection)
hilt-android = "2.44"
hilt-compiler = "2.44"

# Coil (Image Loading)
coil = "2.4.0"

timber = "5.0.1"
annotation = "1.6.0"



[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Lifecycle
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }

# Navigation
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-ui-ktx" }

# Room Database
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-ktx" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-compiler" }

# Coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-core" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines-android" }

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit-gson" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-compiler" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }


# Coil
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }



[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }